import {Link} from "react-router-dom";
import Logo from "./Logo";
import { SignedIn, SignedOut, useClerk, UserButton } from "@clerk/clerk-react";

const Menubar = () => {

    const {openSignIn} = useClerk();

    const openLogin = () => {
        openSignIn({});
    }

    return(
        <nav className="navbar navbar-expand-lg navbar-light bg-white shadow-sm sticky-top">
            <div className="container py-2">
                <Link className="navbar-brand d-flex align-items-center" to="/">
                    <Logo />
                    <span className="fw-bolder fs-4-mx-3" style={{ letterSpacing: '-0.5px', color: '#0D6EFDB2' }}>
                        InvoEase 
                    </span>
                </Link>

                <button 
                    className="navbar-toggler" 
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navigatorbarNav"
                    aria-controls="navbarNav"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span className="navbar-toggler-icon"></span>
                </button>

                <div className="collapse navbar-collapse" id="navigatorbarNav">
                    <ul className="navbar-nav ms-auto align-items-center gap-4">
                        <li className="nav-item">
                            <Link className="nav-link fw-medium" to="/">
                                Home
                            </Link>
                        </li>

                        {/* Dashboard and Generate will only appear once signed in */}
                        <SignedIn>
                            <li className="nav-item">
                                <Link className="nav-link fw-medium" to="/dashboard">
                                    Dashboard
                                </Link>
                            </li>
                            <li className="nav-item">
                                <button className="nav-link fw-medium">
                                    Generate
                                </button>
                            </li>

                            <UserButton />
                        </SignedIn>

                        {/* This will only appear once the user logs out in the app */}
                        {/* Creates a pop-out window generated by Clerk for users to log in their accounts */}
                        <SignedOut>
                            <li className="nav-item">
                                <button className="btn btn-primary rounded-pill px-4" onClick={openLogin}>
                                    Login / Sign Up
                                </button>
                            </li>
                        </SignedOut>
                        
                    </ul>
                </div>
            </div>
        </nav>
    );
}

export default Menubar;